version: 2
jobs:
  build:
    docker:
      - image: buildpack-deps:trusty
      - image: circleci/php:7.1.4-browsers
      - image: circleci/mysql:5.7.18

    branches:
      only:
        - develop

    working_directory: ~/repo

    steps:
      - checkout
      - run: |
          echo 127.0.0.1 circlehost | sudo tee -a /etc/hosts

      - run: |
          mysql -u ubuntu -e "create database wordpress"

      - run: |
          curl -O "https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar"
          chmod +x wp-cli.phar

      - run: |
          ./wp-cli.phar core download --allow-root --path=wordpress

      - run: |
          git clone git@github.com:Themekraft/wc4bp.git wordpress/wp-content/plugins/wc4bp-premium

      - run: |
          ./wp-cli.phar plugin activate wc4bp-premium --path=wordpress

      - run: |
          ./wp-cli.phar plugin list --path=wordpress